- pom.xml
Resolves: [BI-5264](https://companieshouse.atlassian.net/browse/BI-5264)
> Updating the POM to fix Sonar reporting

- spec/swagger.json
- src/main/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentController.java
- src/main/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplate.java
- src/test/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplateTest.java
- add 'company_number' to '/payment' response JSON
- update spec accordingly (v0.2.2)
Resolves:
BI-5722
> Fix "company_number" absent in '/payment' response

- src/main/resources/form_templates.json
Small additions to form descriptions..
BI-5711
BI-5712
> Changes to text description for Resolutions and 600 form

- README.md
add this to README under 'Building and Running Locally':
> adding details of db collections reqd by service

- src/main/java/uk/gov/companieshouse/efs/api/events/service/SqsMessageService.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/model/Submission.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/CompanyDetailsValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/ConfirmAuthorisedValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/ConfirmationReferenceValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/FesAttachmentValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/FileDetailsValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/FormDetailsValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/FormTemplateValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/PaymentSessionsValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/PresenterValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/SubmissionValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/Validator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/ValidatorImpl.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/CompanyDetailsValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/ConfirmAuthorisedValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/ConfirmationReferenceValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/FesAttachmentValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/FileDetailsValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/FormDetailsValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/FormTemplateValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/PaymentSessionsValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/PresenterValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/SubmissionValidatorTest.java
- refactor complex SubmissionValidator logic into validators using Chain of Responsibility pattern
- add/replace unit tests to maintain test coverage
Resolves:
BI-5561
> Fix sonar issues incl. method complexity

- src/main/resources/form_templates.json
Changed LL RP CH01 name and description in form_templates.json. The ID remains unchanged.
Resolves: [BI-5175](https://companieshouse.atlassian.net/browse/BI-5175)
> Changed LL RP CH01 name and description

- src/main/resources/category_templates.json
Fixed the capitalisation of "rules" in the names of INSEW2016 and INSSC2018
Resolves: [BI-5173](https://companieshouse.atlassian.net/browse/BI-5173)
> Fixed capitalisation of category names

- src/main/resources/form_templates.json
Previous PR accidentally changed the ID not the form name. This PR corrects that.
> Fix form ID change

- pom.xml
> Update private-api-sdk-java version

- src/main/java/uk/gov/companieshouse/efs/api/email/FormCategoryToEmailAddressService.java
- src/test/java/uk/gov/companieshouse/efs/api/email/FormCategoryToEmailAddressServiceTest.java
To trigger the error I added a form to the `form_templates` collection with a `null` id
Application fails to start still.
```
"_id" : null,
"formName" : "BAD",
...
```
BI-5865
> Adding logging message to help identify error when form data is loaded

- src/main/java/uk/gov/companieshouse/efs/api/events/service/ExecutionEngine.java
> Removing unwanted todo comment

- src/main/resources/form_templates.json
Add the necessary msg ids for web to display the appropriate text on Document Upload screen.
(No work required in web, cos the text required is existing already.)
BI-6638
> Add msg id texts for Change of Constitution forms

- src/main/resources/form_templates.json
All existing text so no web changes required.
BI-6660
> Add msg text ids for SQP and SLP forms

- src/main/resources/form_templates.json
Add the necessary msg ids for web to display the appropriate text on Document Upload screen.
- AM01 to AM25.  No Scottish versions
- No work required in web, cos the text required is existing already
BI-6689
> Add message text ids for E/W Insolvency AM forms 

- src/main/resources/form_templates.json
- refactor common text used by SH06
> Add custom text for Insolvency forms MT01 to MT09

- src/main/resources/form_templates.json
> Adding messageTextIdList to AD01

- src/main/resources/form_templates.json
For release 27 at the moment.
BI-6694
> Add msg text id for NOCP form

- src/main/resources/form_templates.json
> Add custom text for COM1 to COM4

- src/main/resources/form_templates.json
> Adding messageTextIdList values for WU forms

- src/main/resources/form_templates.json
> Adding messageTextIdList for REC and RM forms

- src/main/resources/form_templates.json
- Added relevant messageTextIds to the form_templates
- No web changes as the text is already in the web
> Added dynamic text on the upload screen for CVA forms

- src/main/resources/form_templates.json
No web changes as the text is already present in the web
> Added dynamic text on the upload page for NDISC forms

- Tiltfile.dev
Database name should use underscore, not a hyphen .
> Corrected variable name for database name

- src/main/java/uk/gov/companieshouse/efs/api/email/model/EmailDocument.java
- src/main/java/uk/gov/companieshouse/efs/api/email/model/PaymentReportEmailData.java
> Addressing static base class issue

- pom.xml
upgrade to latest available versions to satisfy security vulnerability
have successfully built and used service through to payment and confirmation screen
BI-7773
BI-7774
> Upgrade commons-io and guava versions

- src/main/resources/payment_templates.json
Add the payment template for the SH19
BI-5543
> Add the payment details for the SH19

- src/main/resources/category_templates.json
Updated the hint text for the SH category to match the prototype.
[BI-6496](https://companieshouse.atlassian.net/browse/BI-6496)
> Updated share capital hint text

- pom.xml
- src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/controller/CategoryTemplateController.java
- src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/mapper/CategoryTemplateMapper.java
- src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTemplate.java
- src/main/resources/category_templates.json
- src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/controller/CategoryTemplateControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/mapper/CategoryTemplateMapperTest.java
- src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTemplateTest.java
- src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/service/CategoryTemplateServiceImplTest.java
Reverts companieshouse/efs-submission-api#55
> Revert "Extend dynamic guidance to category / document selection screens"

- src/main/resources/form_templates.json
Amend the msg text ids for the 4 new share capital forms
BI-6840
> change the text ids for the new share capital forms

- pom.xml
- src/main/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/formtemplates/mapper/FormTemplateMapper.java
- src/main/java/uk/gov/companieshouse/efs/api/formtemplates/model/FormTemplate.java
- src/main/resources/form_templates.json
- src/test/java/uk/gov/companieshouse/efs/api/companyauthallowlist/service/CompanyAuthAllowListServiceImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/DecisionEngineTest.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/formtemplates/mapper/FormTemplateMapperTest.java
- src/test/java/uk/gov/companieshouse/efs/api/formtemplates/model/FormTemplateTest.java
- src/test/java/uk/gov/companieshouse/efs/api/formtemplates/service/FormTemplateServiceImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/FormTemplateValidatorTest.java
When submitting to FES database
- use `fesDocType` property if present
- otherwise use `formType` property
Resolves:
BI-8196
BI-6575
> Add `fesDocType` property for FormTemplate

- src/main/resources/form_templates.json
> Remove empty form template causing API startup failure

- src/main/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImpl.java
- src/main/resources/form_templates.json
- src/test/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImplTest.java
Investigate 500 from NullPointerException after `POST /events/submit-files-to-fes` request
> Fix form type ID `RESOLUTIONS` backward compatibility

- src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTypeConstants.java
- src/main/java/uk/gov/companieshouse/efs/api/email/FormCategoryToEmailAddressService.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/efs/api/email/FormCategoryToEmailAddressServiceTest.java
- src/test/resources/application.properties
- add config env var INTERNAL_SHARE_CAPITAL_REDUCTION_EMAIL_ADDRESS
- update mapping of SH-RED category forms to that email address
Resolves:
BI-8206
> Add separate business email address for delayed SH-RED forms

- src/main/java/uk/gov/companieshouse/efs/api/email/model/ExternalRejectEmailData.java
- src/test/java/uk/gov/companieshouse/efs/api/email/model/ExternalRejectEmailDataTest.java
- implement Builder pattern described at
https://blog.tratif.com/2017/11/17/builder-pattern-revisited/
also removing duplicated fields in Builder class
Resolves:
BI-7120
> Fix Sonar BI-7120: too many method parameters

- src/main/java/uk/gov/companieshouse/efs/api/email/model/ExternalConfirmationEmailData.java
- src/test/java/uk/gov/companieshouse/efs/api/email/model/ExternalConfirmationEmailDataTest.java
- implement Builder pattern described at
https://blog.tratif.com/2017/11/17/builder-pattern-revisited/
also removing duplicated fields in Builder class
Resolves:
BI-7119
> Fix Sonar issue: too many method parameters

- pom.xml
BI-8486
Also https://github.com/companieshouse/efs-submission-web/pull/87
> Update jib-maven-plugin to latest to fix build

- src/main/java/uk/gov/companieshouse/efs/api/email/EmailService.java
- src/main/java/uk/gov/companieshouse/efs/api/email/EmailServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/events/service/SameDayServiceDelayedHandler.java
- src/main/resources/application.properties
- src/test/java/uk/gov/companieshouse/efs/api/email/EmailServiceImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/SameDayServiceDelayedHandlerTest.java
- add configuration for SH19 email address
- send copy of support email to SH19 email address
Resolves:
BI-8467
> Send copy of support email to SH19 business team

- src/main/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepositoryImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/util/CurrentTimestampGenerator.java
- src/test/java/uk/gov/companieshouse/efs/api/util/CurrentTimestampGeneratorTest.java
> Add logging of timestamps [UTC]

- src/main/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImpl.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepositoryImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImplTest.java
> Fix broken unit tests with timestamps

- src/main/java/uk/gov/companieshouse/efs/api/util/CurrentTimestampGenerator.java
Removed unused imports from CurrentTimestampGenerator.java
https://companieshouse.atlassian.net/browse/BI-8763
> Removed unused imports

- src/main/java/uk/gov/companieshouse/efs/api/email/model/InternalAvFailedEmailData.java
Fixed too many parameters issue in InternalAvFailedEmailData.java using builder class
https://companieshouse.atlassian.net/browse/BI-7126
> Fixed too many parameters issue in InternalAvFailedEmailData.java

- src/main/java/uk/gov/companieshouse/efs/api/email/model/InternalFailedConversionEmailData.java
Fixed too many parameters in InternalFailedConversionEmailData.java using builder class
https://companieshouse.atlassian.net/browse/BI-7128
> Fixed too many parameters in InternalFailedConversionEmailData.java

- src/main/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepository.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepositoryImpl.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepositoryImplTest.java
- create priority ordering SubmissionRepository.findByStatusOrderByPriority()
Resolves:
BI-11140
> Prioritise same day submissions

- src/main/java/uk/gov/companieshouse/efs/api/events/service/BarcodeGeneratorServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/filetransfer/FileTransferApiResponseHandler.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/controller/ConfirmAuthorisedController.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/controller/ConfirmFormTypeController.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/BarcodeGeneratorServiceImplTest.java
Sonar issues - avoid a possible NPE in 4 classes by using Optionals
BI-11201
> Fix Sonar issue to avoid a NPE

- src/main/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/fes/service/FesServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/mapper/SubmissionApiMapper.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/model/Submission.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImpl.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/fes/service/FesServiceImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/mapper/SubmissionApiMapperTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/mapper/SubmissionMapperTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImplTest.java
Fix too many parameters issue in Submission.java using builder class 
https://companieshouse.atlassian.net/browse/BI-7138
> Fix too many parameters issue in Submission.java using builder class

- src/main/java/uk/gov/companieshouse/efs/api/interceptor/LoggingInterceptor.java
- src/main/java/uk/gov/companieshouse/efs/api/interceptor/UserAuthenticationInterceptor.java
Updated use of deprecated HandlerInterceptorAdapter to use HandlerInterceptor instead
https://companieshouse.atlassian.net/browse/BI-8135
> Updated use of deprecated HandlerInterceptorAdapter

- src/main/resources/form_templates.json
Adding orderIndex values for Insolvency forms in these parent categories:
B1-11087 - CIGA2000
BI-11090 - IA1986_CVAM
BI-11091 - IA1986_ADM
BI-11092 - IA1986_REC
> Adding orderIndex for four Insolvency categories

- src/main/resources/form_templates.json
Resolves:
BI-11127
BI-11128
BI-11129
BI-11130
> Add orderIndex for OCR2009/LLPR2009/INS_RES/INSCROA forms

- src/main/resources/form_templates.json
Resolves:
BI-11112
BI-11114
BI-11115
BI-11116
BI-11117
BI-11118
BI-11119
BI-11120
> Add orderIndex for INSSC2018_ADM/COM/CVA/CVAM/EXP/VL/REC/WU forms

- src/main/resources/form_templates.json
Resolves:
BI-11123
BI-11124
BI-11125
BI-11126
> Add orderIndex for INIO198918_CVAM/ADM/REC/LIQ forms

- src/main/resources/category_templates.json
Resolves:
BI-11085
BI-11086
BI-11088
BI-11099
BI-11111
BI-11121
BI-11132
> Add orderIndex values to Category data

- src/main/resources/form_templates.json
> Fix forms with missing orderIndex values

- src/main/java/uk/gov/companieshouse/efs/api/events/service/DelayedSubmissionHandlerContext.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/SubmissionValidator.java
- src/test/java/uk/gov/companieshouse/efs/api/email/mapper/PaymentReportEmailMapperTest.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/DelayedSubmissionHandlerContextTest.java
1. Remove this useless assignment to local variable "resultStatus" -  https://code-analysis.platform.aws.chdev.org/project/issues?id=uk.gov.companieshouse%3Aefs-submission-api&issues=AYCPoQvg6UzS8-qLi4L0&open=AYCPoQvg6UzS8-qLi4L0
2. Add the "@Override" annotation above this method signature - https://code-analysis.platform.aws.chdev.org/project/issues?id=uk.gov.companieshouse%3Aefs-submission-api&issues=AX29f1Wp6UzS8-qLuVzL&open=AX29f1Wp6UzS8-qLuVzL
3. Replace these 3 tests with a single Parameterized one - https://code-analysis.platform.aws.chdev.org/project/issues?id=uk.gov.companieshouse%3Aefs-submission-api&issues=AX29f1K36UzS8-qLuVy5&open=AX29f1K36UzS8-qLuVy5
4. Replace this use of System.out or System.err by a logger - https://code-analysis.platform.aws.chdev.org/project/issues?id=uk …
> Sonar fixes in code and test

- Makefile
- pom.xml
- suppress.xml
- add dependency check to maven and make builds
- bump companies-house-parent POM to 1.3.1
- bump structured-logging to 1.9.14
- fix sonar report path: coverage XML not uploading to sonarqube
Resolves:
BI-13349
> Add OWASP dependency check to build

- src/main/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/PaymentSessionsValidator.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/SubmissionValidator.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/PaymentSessionsValidatorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/SubmissionValidatorTest.java
- fix submission of fee-bearing form not having any payment sessions but passing validation
Resolves:
FEE-192
> Fix validation false positive on conpleting submission

- pom.xml
- src/main/java/uk/gov/companieshouse/efs/api/paymentreports/service/PaymentReportService.java
- src/main/java/uk/gov/companieshouse/efs/api/paymentreports/service/PaymentReportServiceImpl.java
- src/test/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplateTest.java
- src/test/java/uk/gov/companieshouse/efs/api/paymentreports/service/PaymentReportServiceImplTest.java
- suppress.xml
- bump Spring Boot version to 2.7.17 (highest supporting JDK 8)
- fix deprecated code
- add test coverage for changes
- suppress spring-web-5.3.30 for 6 months (requires JDK 17)
Resolves:
BI-13368
> Address security vulnerabilites

- src/main/java/uk/gov/companieshouse/efs/api/email/EmailServiceImpl.java
> Investigate efs confirmation screen failing

- pom.xml
> Replace kafka-clients 3.1.2 with 0.10.2.2

- README.md
- Add clarification on date formatting
> Update README.md - planned maintenance config Notes

- pom.xml
Use parent pom to retrieve version and key for nvd api check rather than data feed.
> use parent pom for dep check

- Makefile
- pom.xml
- src/it/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerDatabaseIT.java
- src/it/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerIT.java
- src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/controller/CategoryTemplateController.java
- src/main/java/uk/gov/companieshouse/efs/api/events/controller/DocumentConvertedController.java
- src/main/java/uk/gov/companieshouse/efs/api/filetransfer/model/FileTransferApiClientDetailsResponse.java
- src/main/java/uk/gov/companieshouse/efs/api/formtemplates/controller/FormTemplateController.java
- src/main/java/uk/gov/companieshouse/efs/api/interceptor/AuthenticationHelper.java
- src/main/java/uk/gov/companieshouse/efs/api/interceptor/AuthenticationHelperImpl.java
- src/main/java/uk/gov/companieshouse/efs/api/interceptor/LoggingInterceptor.java
- src/main/java/uk/gov/companieshouse/efs/api/interceptor/UserAuthenticationInterceptor.java
- src/main/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentController.java
- src/main/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentFeatureTestingFeesController.java
- src/main/java/uk/gov/companieshouse/efs/api/submissions/controller/PendStatusController.java
- src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/controller/CategoryTemplateControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/companyauthallowlist/controller/CompanyAuthAllowListControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/events/controller/DocumentConvertedControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/S3ClientServiceTest.java
- src/test/java/uk/gov/companieshouse/efs/api/events/service/fesloader/BatchDaoTest.java
- src/test/java/uk/gov/companieshouse/efs/api/formtemplates/controller/FormTemplateTemplateControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/interceptor/AuthenticationHelperImplTest.java
- src/test/java/uk/gov/companieshouse/efs/api/interceptor/LoggingInterceptorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/interceptor/UserAuthenticationInterceptorTest.java
- src/test/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerTest.java
- src/test/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplateTest.java
- src/test/java/uk/gov/companieshouse/efs/api/submissions/controller/PendSubmissionControllerTest.java
https://companieshouse.atlassian.net/browse/JU-57
> Java 21 migration dev wrok for efs-submission-api

- docker-compose.yml
- pom.xml
> Ju 57 java21 migration mnycz dev

- pom.xml
> JU-57 update docker image

- README.md
efs-submission-api
adding ecs information to the README
> JU-777 adding ecs info to README

- src/main/java/uk/gov/companieshouse/efs/api/email/mapper/PaymentReportEmailMapper.java
- src/test/java/uk/gov/companieshouse/efs/api/email/mapper/PaymentReportEmailMapperTest.java
Reverted the original change to the payment report functionality
> BI-14134 revert scottish payment email change

- terraform/groups/ecs-service/main.tf
**Jira ticket**: [JU-1755](https://companieshouse.atlassian.net/browse/JU-1755)
[JU-1755]: https://companieshouse.atlassian.net/browse/JU-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> platform tech debt 
