companieshouse/efs-submission-api

src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTypeConstants.java, src/main/java/uk/gov/companieshouse/efs/api/email/mapper/ExternalConfirmationEmailMapper.java, src/main/java/uk/gov/companieshouse/efs/api/email/model/ExternalConfirmationEmailData.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/service/CategoryTemplateServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/config/ConfigTest.java, src/test/java/uk/gov/companieshouse/efs/api/email/mapper/ExternalConfirmationEmailMapperTest.java
Registrar Powers forms that are accepted will be followed up with a letter to explain what happens next.
This needs to be reflected in the confirmation email text.
PR for email templates - https://github.com/companieshouse/chs-notification-api/pull/233
BI-5556
Unit tests updated ✔️
=> Add 'Top level Category' to data in Confirmation email

src/main/java/uk/gov/companieshouse/efs/api/submissions/validator/PaymentSessionsValidator.java, src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/PaymentSessionsValidatorTest.java
- fix PaymentSessionsValidator not failing when FormTemplate.fee is blank and Submission has payment sessions
Resolves:
BI-5561
=> Fix payment sessions validation bug

src/main/java/uk/gov/companieshouse/efs/api/paymentreports/service/PaymentReportServiceImpl.java, src/main/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepository.java, src/main/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepositoryImpl.java, src/test/java/uk/gov/companieshouse/efs/api/paymentreports/service/PaymentReportServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/submissions/repository/SubmissionRepositoryImplTest.java
- fix error in report start date calculation
- ensure the report period is always 1 day long and
$REPORT_PERIOD_DAYS_BEFORE_TODAY days ago
Resolves:
BI-5535
=> Fix Submissions appearing on more than one payment report

src/main/resources/form_templates.json
Add the msg text ids required for web to dynamically display text on Document Upload screen.
BI-6639
Corresponding web PR: https://github.com/companieshouse/efs-submission-web/pull/39
=> Add msg text ids for all existing Share Capital forms

src/main/resources/form_templates.json
Add the necessary msg ids for web to display the appropriate text on Document Upload screen.
- VAM1 to VAM7 and VAMC.  No Scottish versions
- No work required in web, cos the text required is existing already
BI-6688
=> Add message text ids for E/W Insolvency VAM forms

src/main/resources/form_templates.json
Added dynamic guidance text on the upload screen for the LIQ forms. 
The dynamic text was already present in the web so the only change was to add relevant `messageTextIdList` values for LIQ01-LIQ14 in the `form_templates.json`.
Resolves: [BI-6691](https://companieshouse.atlassian.net/browse/BI-6691)
=> Added custom text on the upload screen for LIQ forms

src/main/java/uk/gov/companieshouse/efs/api/email/FormCategoryToEmailAddressService.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/efs/api/email/FormCategoryToEmailAddressServiceTest.java
- adds a configurable property for Scotland and Northern Ireland company prefixes
- checks through those lists
- add a few more unit tests for these prefixes
Corresponding config PR: https://github.com/companieshouse/chs-configs/pull/1430
BI-6744
I went thru' every prefix listed and a few made up ones, email addresses as expected:
=> Add partnership company prefixes for Internal email

Tiltfile.dev
Bash script that reload database values was using the wrong variable name. That is now fixed.
=> Corrected variable name for database name

src/main/java/uk/gov/companieshouse/efs/api/email/mapper/ExternalConfirmationEmailMapper.java, src/main/java/uk/gov/companieshouse/efs/api/email/model/ExternalConfirmationEmailData.java, src/test/java/uk/gov/companieshouse/efs/api/email/mapper/ExternalConfirmationEmailMapperTest.java
The `fee_on_submission` is already present in the submission data when appropriate.  
This just adds it to the ConfirmationEmailData.
email template PR: https://github.com/companieshouse/chs-notification-api/pull/257
BI-7082
=> Add payment to confirmation email data

pom.xml
As part of a CHS Mongo upgrade, the drivers used also need to be updated. 
- These are set in the spring-boot dependencies and the latest is `2.4.4`
https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies
- I have built and checked that data is stored in the db.
Jira: BI-7083
=> Upgrade spring-boot-dependencies to 2.4.4

pom.xml
- add spring-boot-starter-validation dependency removed from spring-boot-starter
- bump junit 5 to version 5.7.1
- bump mockito version to 3.8.0
- add mockito-inline dependency for mocking final classes/methods
Resolves:
BI-7083
=> Fix Boot validation after version upgrade

src/main/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplate.java, src/main/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImpl.java, src/test/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImplTest.java
- keep submission status OPEN; allow user to retry payment
- reorder methods in PaymentTemplate.Status to avoid duplicate code detection
Resolves:
BI-7733
=> Fix payment PATCH for failed outcome called BEFORE completion

pom.xml, src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/controller/CategoryTemplateController.java, src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/mapper/CategoryTemplateMapper.java, src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTemplate.java, src/main/resources/category_templates.json, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/controller/CategoryTemplateControllerTest.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/mapper/CategoryTemplateMapperTest.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTemplateTest.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/service/CategoryTemplateServiceImplTest.java
This PR supports this [web PR](https://github.com/companieshouse/efs-submission-web/pull/76).
Adds support for a new field in the category template collection to specify guidance text fragment IDs so that they can be displayed on the category and document selection screens.
[BI-7097](https://companieshouse.atlassian.net/browse/BI-7097)
=> Extend dynamic guidance to category / document selection screens

src/main/resources/form_templates.json
see the sql we've done in BI-6252 and BI-6256.
Have confirmed with Leon that no hyphens should be used.
BI-8212
=> fix for BI-8212 Spec Cap res is 'S CAP RES' on FES and CHIPS

src/main/java/uk/gov/companieshouse/efs/api/email/mapper/ExternalRejectEmailMapper.java, src/main/java/uk/gov/companieshouse/efs/api/email/model/ExternalRejectEmailData.java, src/test/java/uk/gov/companieshouse/efs/api/email/mapper/ExternalRejectEmailMapperTest.java
Added field "isPaidForm" to rejection email model so that a paragraph about refunds can be dynamically added to rejection emails when the form is paid. 
Associated chs-notification-api PR: https://github.com/companieshouse/chs-notification-api/pull/277
[BI-8064](https://companieshouse.atlassian.net/browse/BI-8064)
=> Add refund information to rejection email when paid form

src/main/resources/payment_templates.json
- `_id` is what we've agreed for a new form in the form_templates
- `product_type` aligns with the prod code in the [payment reconciliation PR](https://github.com/companieshouse/payment-reconciliation-consumer/pull/36)
- `description_identifier` is what I assume is correct
I've tested by adding a SH19_SAMEDAY to my form_templates and payment service is as expected
BI-7846
=> Add payment template SH19 sameday

pom.xml, spec/swagger.json, src/main/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImpl.java, src/main/java/uk/gov/companieshouse/efs/api/events/service/FesLoaderServiceImpl.java, src/main/java/uk/gov/companieshouse/efs/api/events/service/fesloader/FormDao.java, src/main/java/uk/gov/companieshouse/efs/api/events/service/model/FesLoaderModel.java, src/main/java/uk/gov/companieshouse/efs/api/events/service/model/FormModel.java, src/main/java/uk/gov/companieshouse/efs/api/formtemplates/mapper/FormTemplateMapper.java, src/main/java/uk/gov/companieshouse/efs/api/formtemplates/model/FormTemplate.java, src/main/resources/form_templates.json, src/test/java/uk/gov/companieshouse/efs/api/events/service/DecisionEngineTest.java, src/test/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/events/service/FesLoaderServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/events/service/fesloader/FormDaoTest.java, src/test/java/uk/gov/companieshouse/efs/api/events/service/model/FesLoaderModelTest.java, src/test/java/uk/gov/companieshouse/efs/api/events/service/model/FormModelTest.java, src/test/java/uk/gov/companieshouse/efs/api/formtemplates/mapper/FormTemplateMapperTest.java, src/test/java/uk/gov/companieshouse/efs/api/formtemplates/model/FormTemplateTest.java, src/test/java/uk/gov/companieshouse/efs/api/formtemplates/service/FormTemplateServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerTest.java, src/test/java/uk/gov/companieshouse/efs/api/submissions/validator/FormTemplateValidatorTest.java
- update API spec; add form template property isSameDayService
- update API spec; change /form-template path param to query param
- use FormTemplateApi property isSameDay()
- apply builder pattern to FormModel
- apply builder pattern to FormTemplate
- add SH19_SAMEDAY to form_templates.json
- include unit test coverage
Resolves:
BI-7848
=> Support FES same day indicator for form templates

src/main/java/uk/gov/companieshouse/efs/api/paymentreports/service/PaymentReportServiceImpl.java, src/test/java/uk/gov/companieshouse/efs/api/paymentreports/service/PaymentReportServiceImplTest.java
BI-7969 & defect BI-8465
Unit test amended/added to check presence of transactions when SH19 / SH19_SAMEDAY submissions - (credit @hepsimo)
Report now includes all SH19's:
=> Filter paymentTransactions starting with SH19 instead of equal to SH19

src/main/resources/category_templates.json, src/main/resources/form_templates.json
Update Category and Form templates for SH19 same day
- add parent category for form `SH19_SAMEDAY` outside category hierarchy
- update `SH19_SAMEDAY` description to meet requirements on Check Details page
- requires `efs-submissions-web` changes for BI-7844 (PR pending); do not apply beforehand
Resolves:
BI-7844
See also:
BI-8066
=> Add support for SH19 same day form

src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/service/CategoryTemplateServiceImpl.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/service/CategoryTemplateServiceImplTest.java
- avoid infinite loop in `getTopLevelCategory()` for a category having itself in hierarchy, e.g. SH-RED-SAMEDAY has parent=SH-RED-SAMEDAY
Resolves:
BI-8490
=> Fix bug in getTopLevelCategory() for SH-RED-SAMEDAY

pom.xml
Fix for log4j security vulnerability
DEBT-1446
Have run service and logs displayed as expected
`➜  efs-submission-api mvn dependency:tree | grep log4j`
`[INFO] |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.16.0:compile`
`[INFO] |  |  \- org.apache.logging.log4j:log4j-api:jar:2.16.0:compile`
`[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.16.0:compile`
=> Updated version of log4j to 2.16.0

src/main/resources/application.properties
Currently in tcats1 it's `https://internalapi.tcats1.aws.chdev.org/efs-submission-api/health`
Correct to `/efs-submission-api/healthcheck`
BI-9879
Matches spec in https://github.com/companieshouse/styleguides/blob/main/health_check.md
These config values are already present in `chs-configs` and in live `app_env`
=> Amend healthcheck url to be 'efs-submission-api/healthcheck'

src/main/java/uk/gov/companieshouse/efs/api/events/service/FesLoaderServiceImpl.java
To better understand the duration needed to insert into FES a timer was added to the insertIntoFes method. This duration is added to the debug log message that is emitted at the end of the method. The duration is logged in the format `0m:0s:000ms`.
Resolves: [BI-11141](https://companieshouse.atlassian.net/browse/BI-11141)
=> Duration to insert into FES now added to log message

src/main/java/uk/gov/companieshouse/efs/api/events/service/FesLoaderServiceImpl.java, src/main/resources/application.properties, src/test/java/uk/gov/companieshouse/efs/api/events/service/EventServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/events/service/FesLoaderServiceImplTest.java
- add Spring transaction timeout to FesLoaderServiceImpl.insertSubmission
- configure timeout with FES_JDBC_TIMEOUT_SECONDS env var
Resolves:
BI-11139
=> Add configurable FES datasource transaction timeout

src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTemplate.java, src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/repository/CategoryTemplateRepository.java, src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/service/CategoryTemplateServiceImpl.java, src/main/java/uk/gov/companieshouse/efs/api/formtemplates/model/FormTemplate.java, src/main/java/uk/gov/companieshouse/efs/api/formtemplates/repository/FormTemplateRepository.java, src/main/java/uk/gov/companieshouse/efs/api/formtemplates/service/FormTemplateServiceImpl.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/mapper/CategoryTemplateMapperTest.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/model/CategoryTemplateTest.java, src/test/java/uk/gov/companieshouse/efs/api/categorytemplates/service/CategoryTemplateServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/formtemplates/model/FormTemplateTest.java, src/test/java/uk/gov/companieshouse/efs/api/formtemplates/service/FormTemplateServiceImplTest.java
Apply sorting to repository methods fetching Form and Category templates belonging to a parent category using the new optional integer property 'orderIndex'
- Templates without an 'orderIndex' value will sort before those with one.
- Templates sort by orderIndex in ascending order
Summary of which API endpoints for form & category templates are enhanced to order the response data if orderIndex values are provided in the database:
| API Endpoint | Ordering within Parent |
|--------------|------------------|
| `/form-templates` | ⚪ No |
| `/form-template/{form-id}` | ⚪ No |
| `/form-templates?category={category-id}` | ✅ Yes |
| `/category-templates` | ⚪ No |
| `/category-template/{category-id}` | ⚪ No |
| `/category-template/` | ⚪ No |
| `/category-templates?parent={category-id}` | ✅ Yes |
=> Add child order to form & category templates

src/main/java/uk/gov/companieshouse/efs/api/events/service/DelayedSubmissionHandlerContext.java, src/main/java/uk/gov/companieshouse/efs/api/events/service/fesloader/BatchDao.java, src/test/java/uk/gov/companieshouse/efs/api/events/service/fesloader/BatchDaoTest.java
Fix for deprecated 'queryForObject' method as per
https://stackoverflow.com/questions/65301011/jdbctemplate-queryforobject-and-query-is-deprecated-in-spring-what-should-i
I have tested that form sent to FES and batch name was generated as expected `EFS_220628_0001` and `EFS_220628_0002`
BI-8133
=> Replace version of 'queryForObject' method

Tiltfile.dev, docker-compose.yml, pom.xml, src/it/java/uk/gov/companieshouse/efs/api/payment/controller/MongoDbTestContainerConfig.java, src/it/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerDatabaseIT.java, src/it/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerIT.java, src/main/java/uk/gov/companieshouse/efs/api/categorytemplates/controller/CategoryTemplateController.java, src/main/java/uk/gov/companieshouse/efs/api/companyauthallowlist/controller/CompanyAuthAllowListController.java, src/main/java/uk/gov/companieshouse/efs/api/formtemplates/controller/FormTemplateController.java, src/main/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentController.java, src/main/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerSpike.java, src/main/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentFeatureTestingFeesController.java, src/main/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplate.java, src/main/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplateId.java, src/main/java/uk/gov/companieshouse/efs/api/payment/repository/PaymentTemplateRepository.java, src/main/java/uk/gov/companieshouse/efs/api/payment/service/PaymentTemplateService.java, src/main/java/uk/gov/companieshouse/efs/api/payment/service/PaymentTemplateServiceImpl.java, src/main/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImpl.java, src/main/resources/application.properties, src/main/resources/payment_templates.json, src/test/java/uk/gov/companieshouse/efs/api/payment/controller/PaymentControllerTest.java, src/test/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplateIdTest.java, src/test/java/uk/gov/companieshouse/efs/api/payment/entity/PaymentTemplateTest.java, src/test/java/uk/gov/companieshouse/efs/api/payment/service/PaymentTemplateServiceImplTest.java, src/test/java/uk/gov/companieshouse/efs/api/payment/service/PaymentTemplateServiceTest.java, src/test/java/uk/gov/companieshouse/efs/api/submissions/service/SubmissionServiceImplTest.java, src/test/resources/application.properties
Support activation dates for form payment templates:
- allow multiple payment templates associated with the same form template,  each with a separate activation date (including future dates)
- for the `submission/{id}/payment` endpoint, enhance lookup of the selected form's payment template by selecting the currently active one
- expose test/diagnostic endpoints with feature flag `$FEATURE_TESTING_FEES`, defaults to `false`
1.  `GET /payment-templates?type=<FEE_ID>&activeAt=<CHARGE_DATE_TIME>`: find the current fees for the form template `FORM_TEMPLATE`: select the associated payment template having the latest activation date that is not after `CHARGE_DATE_TIME`
- e.g. `GET /payment-templates?fee=SLPCS01&chargedAt=2023-10-01T12:34:56`
1. `/payment-templates?fee=<FEE_ID>`: find all payment …
=> EFS API: Add support from payment template activation dates

pom.xml
1.4.9 has a Java version error
=> Move back from ch-kafka version 1.4.9 to 1.4.8

spec/swagger.json, src/main/java/uk/gov/companieshouse/efs/api/maintenance/MaintenanceActuatorEndpoint.java, src/test/java/uk/gov/companieshouse/efs/api/maintenance/MaintenanceActuatorEndpointTest.java
Maintenance check response code should always be 200 OK, even during planned maintenance periods. Response 503 SERVICE UNAVAILABLE causing wrong screen to display in EFS Web.
=> Fix incorrect maintenance screen displayed in EFS Web

src/main/resources/form_templates.json
This is for this screen:
or this can be called `https://internalapi.tcats1.aws.chdev.org/efs-submission-api/form-templates?category=INSSC2018_VL`
BI-13477
=> Add sequential order index to Scottish Liq forms

Makefile, pom.xml
The 'dependency-check' target uses a variable
dependency_check_suppressions_repo_branch
which previously pointed to a different branch:
feature/suppressions-for-company-accounts-api
... but that branch has been merged into main and so this variable should now point to main.
=> Repoint Makefile at dep-check-suppressions/main

pom.xml
Fixes CVE-2024-31141 by temporarily pinning netty-common
=>  Fix for CVE-2024-31141

Makefile, pom.xml, src/main/resources/application.properties
Part of [ASM-239](https://companieshouse.atlassian.net/jira/software/c/projects/ASM/boards/585?selectedIssue=ASM-239). The maintenance work for `efs-submission-api` the `dependency_check_minimum_cvss` (Common Vulnerability Scoring System) was set to 4 and changes were implemented to successfully build this module:
Updates to POM dependencies included:
- general tidy up e.g. update `groupId` in the exclusion for `plexus-sec-dispatcher`
- replacement of `maven.compiler.source` and `maven.compiler.target` with `maven.compiler.release` - to rectify build warning
- upgrade to `spring-boot.version` 3.4.5 to ensure a successful dependency check
As a result of the Spring Boot increment, some `management.enpoints.x` properties were updated/added to ensure the planned maintenance endpoint remained …
=> ASM-239: Remove `efs-sbumission-api` security vulnerabilities
